### ISSUE TITLE
links not working in z/os 2.4 z/osmf upgrade workflow

### ISSUE THREAD

**Issue by imsmark** [IBM/IBM-Z-zOS#126]
I just installed the z/os 2.4 upgrade workflow in z/osmf. I am looking at the Upgrading your zos system. An Introduction. When I click on that and review the information in the top pane of the screen, there are url links. When I click on a link to www.ibm.com..... that works but when I click on a link that points to info from my uss system EX: 
•JES2: Activate z22mode https://td01.rxcorp.com:9443/zosmf/workflow/workflow.jsp#unique_1951480839
these do not work - nothing happens when I click the url link
When I look in /usr/lpp/zosmf/workflow which is where I believe the url points I do not see a workflow.jsp file
Any ideas??

**Comment by jbouzak** [comment]
Thanks for reporting the issue. The issue has been reproduced, and the links are being fixed. The update will be shipped at the end of this month/early next month.

**Comment by jbouzak** [comment]
Addressed by - https://github.com/IBM/IBM-Z-zOS/pull/133
