### ISSUE TITLE
Broken link to oeconsole assembler source

### ISSUE THREAD

**Issue by AnthonyGiorgio** [IBM/IBM-Z-zOS#150]
The [oeconsole readme file](https://github.com/IBM/IBM-Z-zOS/tree/master/zOS-Tools-and-Toys/oeconsol) has a broken link to the [assembler source code](https://github.com/IBM/IBM-Z-zOS/blob/master/zOS-Tools-and-Toys/oeconsol/oeconsol.asm).

**Comment by jbouzak** [comment]
fixed in https://github.com/IBM/IBM-Z-zOS/pull/151
