### ISSUE TITLE
not able to run the sample rest api

### ISSUE THREAD

**Issue by yugeshpothuru** [IBM/IBM-Z-zOS#187]
I'm trying to run the sample rest api from https://github.com/IBM/IBM-Z-zOS/tree/main/zOSMF/ZosmfRESTClient -- but I do not ge any response. I copied the html to a local file and update the ip and invked in I.e and I can the page but when i click on the button nothing happens.

help me with what am i missing to make it work.

thanks
yugesh.

**Comment by ibmliqi** [comment]
Hi, yugesh,

Would you please click F12 in IE to open a new window which contains the developer tools? Then please check if there is any error message under the Console tab when you work with the sample html.

Thanks.
Qi

**Comment by yugeshpothuru** [comment]
Hi Qi,

I'm trying to run it from my pc to get the jobs information from my mainframe.

below is the error that I could see.

SCRIPT7002: XMLHttpRequest: Network Error 0x2ee7, Could not complete the operation due to error 00002ee7.
File: rest-job.html

**Comment by ibmliqi** [comment]
Hi yugesh,

It seems to be a network issue. Could you please try to visit z/OSMF directly from the same browser and see if it works? The URL of z/OSMF can be found in the rest-job.html.

Thanks.

**Comment by yugeshpothuru** [comment]
Hi IQ,

I can do it directly. like https://169.10.244.204/zosmf/api/explorer/#!/Dataset_APIs/GetListDataSets .. I'm able to get it..

but the link https://169.10.244.204:443/zosmf/restfiles/ds?dslevel=a93lnzz.** doesnt work IBM said we need to have a plugin installed for the direct link to work.

thanks
yugesh.

**Comment by ibmliqi** [comment]
Hi, yugesh,

Thanks for sharing the information.

From your description, your PC has correct network connection with the z/OSMF server and you can access the z/OSMF Swagger interface. I don't understand why the connection fails when using the html file. Since IE is already end of service, could you please try with Edge, Firefox or Chrome?

The latest version of browsers might disallow the cross site request, so please configure CORS allow list in your z/OSMF server. Please refer to the "Enabling cross-origin resource sharing (CORS) for REST services" section of the following page for details: https://www.ibm.com/docs/en/zos/2.5.0?topic=guide-using-zosmf-rest-services . This is the typical settings when web applications want to invoke z/OSMF REST services.

Thanks.
Qi.

**Comment by yugeshpothuru** [comment]
Hi Qi,

I dont have the following settings on my system, but I don't see any errors for access controls.
In addition, your user ID requires authorization to the z/﻿OSMF SAF profile prefix on the target z/OS system, as follows:
READ access to <SAF_PREFIX> in the APPL class
READ access to the <SAF_PREFIX>.*.izuUsers profile in the EJBROLE class. Or, at a minimum, READ access to the <SAF_PREFIX>.IzuManagementFacilityRestJobs resource name in the EJBROLE class.

and also we dont have JESJOBS class defined at all

thanks
yugesh,

**Comment by ibmliqi** [comment]
Hi, yugesh,

JESJOBS class is only required by Jobs modification operations. You don't need to configure it if you are not using the Jobs modification function. As you mentioned, you are invoking REST files and data set API, right?

Have you solved the network error in IE please?

Thanks.
Qi.

**Comment by yugeshpothuru** [comment]
Hi Qi,

I dont have any settings that are missing in RACF.

can we try to add "'Authorization':'Basic <encoding of userid:password>'" this to the html code and see if I can get it to work.

thanks
yugesh.

**Comment by ibmliqi** [comment]
Hi, yugesh,

I don't think we need to add the Authorization header in the html. We'd better solve your network error first. Could you please check if your IE 11 is the latest version? Have you tried other types of browers?

Thanks.
Qi.

**Comment by ibmliqi** [comment]
Hi, yugesh,

Could you please confirm if you enabled "Access data sources across domains" in IE 11?  You can enable it on IE by going into Internet Options -> Security Settings ->Custom level and enabling "Access data sources across domains".

Please disable it once you finish the test of the html. 

Thanks.
Qi.

**Comment by yugeshpothuru** [comment]
Hi Qi,

I'm trying to work with my network team.

No response yet from them. I will check on this Ie setting and let you know.

Thanks
Yugesh
