### ISSUE TITLE
links should go to the 2nd url instead of the 1st so the user can see the entire idea with comments. 

### ISSUE THREAD

**Issue by jbouzak** [IBM/IBM-Z-zOS#248]
A suggestion - the table of requriements/ideas links to the idea page (i.e. https://ideas.ibm.com/ideas/ZOS-I-2471) which is fine but not very user friendly - more information can be found on the aha page (i.e. https://ibm-z-hardware-and-operating-systems.ideas.ibm.com/ideas/ZOS-I-2471) - ideally the links should go to the 2nd url instead of the 1st so the user can see the entire idea with comments. (please)

_Originally posted by @lbdyck in https://github.com/IBM/IBM-Z-zOS/issues/246#issuecomment-1775766285_

**Comment by jbouzak** [comment]
@krevans-ibm , I created a new issue to document this idea from

**Comment by jbouzak** [comment]
resolved in #249

**Comment by lbdyck** [comment]
Thank you for taking my suggestion seriously - appreciate it.
