### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by jlczuk** [IBM/IBM-Z-zOS#96]
Why not suggest people open issues right here, in which discussion can be had, including anyone who might be interested.  Or link this with a Jira project so you can setup categories and such.

**Comment by jbouzak** [comment]
Thanks for the suggestion jlczuk. Updated the readme's that pointed to emailing zosmig@us.ibm.com to add the option of opening a github issue as well. 

I didn't update the readme for subdirectories that had other contact info (yet), as I'll have to run the idea by those owners. But I'll be sure that new additions going forward mention this option in the readme.
